pipeline {
    agent any

    stages {
        stage('Task 1: Latest Checkout') {
            steps {
                // Pulls the absolute latest version of your code
                checkout scm
                echo "Workspace updated with the latest commit."
            }
        }

        stage('Task 2: Create File') {
            steps {
                // Task 2: Using Windows BAT to create a file.
                // '>' redirects the echo output into a new file named output.txt
                bat "echo This file was generated by Jenkins Build #${env.BUILD_NUMBER} > output.txt"
                echo "File 'output.txt' has been created in the workspace."
            }
        }

        stage('Task 3: Display File Contents') {
            steps {
                // Task 3: Use the 'type' command (Windows equivalent of 'cat') 
                // to show the file content in the Jenkins console.
                echo "Reading output.txt content:"
                bat "type output.txt"
            }
        }
    }
}